name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore ${{secrets.PATH_UNO}} 
    - name: Build
      run: | 
        dotnet build  ${{secrets.PATH_UNO}} --no-restore
        dotnet publish ${{secrets.PATH_UNO}} --output ./output
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: artifact
        path: /WebApplication1/WebApplication1/output/
        if-no-files-found: error
